name: Update Documentation Symlinks

on:
  push:
    # TODO: This doesn't seem to be working, but I don't know why.
    # BODY: It runs fine on workflow_run, but not on branch push.
    branches: ["gh-pages"]
  workflow_run:
    workflows: ["Publish Documentation", "Release"]
    types: [completed]

jobs:
  symlink:
    name: Update symlinks
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.10.0
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: cd .meta/scripts && npm ci
      - run: node .meta/scripts/update_symlinks.js
      - name: Commit and push
        run: |
          if [ -z "$(git status --porcelain docs)" ]; then
            echo "Nothing to commit, exiting early!"
            exit 0
          fi

          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add docs
          git commit -m "Update version links"
          git push
